import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import mon from "../public/mon.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Richmond Simple Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Richmond</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="mailto: richmondlimar214@gmail.com"
                >
                 Send Email
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Richmond Ramil
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I’m a software engineer specializing in building and designing Martini Designer IDE online. Currently, I’m focused contributing my skills and knowledge to Toro Cloud Limited.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillInstagram />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={mon} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I was <span className="text-teal-500">Frontend Angular JS</span> intern back then and I take the iternship of Toro Cloud Limited. Luckily they gave me a Job offer as <span className="text-teal-500">Software React JS</span> developer after the end of the program
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I offer from a wide range of services, UI/UX design,
              programming, simple MERN stack web sites.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-teal-800 flex-1">
              <Image className="mx-auto" src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white ">
                Beautiful Designs
              </h3>
              <p className="py-2 dark:text-white">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className={darkMode ? "text-sky-600" : "text-teal-600"}>Design Tools I Use</h4>
              <p className={darkMode ? "text-white" : "text-gray-600"}>Photoshop</p>
              <p className={darkMode ? "text-white" : "text-gray-600"}>Illustrator</p>
              <p className={darkMode ? "text-white" : "text-gray-600"}>Figma</p>
              <p className={darkMode ? "text-white" : "text-gray-600"}>Indesign</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-teal-800 flex-1">
              <Image className="mx-auto" src={code} width={100} height={100} alt=""/>
              <h3 className="text-lg dark:text-white font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2 dark:text-white">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className={darkMode ? "text-sky-600" : "text-teal-600"}>Design Tools I Use</h4>
              <p className={darkMode ? "text-white" : "text-gray-600"}>JavaScript</p>
              <p className={darkMode ? "text-white" : "text-gray-600"}>ReactJS</p>
              <p className={darkMode ? "text-white" : "text-gray-600"}>NodeJS</p>
              <p className={darkMode ? "text-white" : "text-gray-600"}>Rest Api</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-teal-800 flex-1">
              <Image className="mx-auto" src={consulting} width={100} height={100} alt=""/>
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-white">Consulting</h3>
              <p className="py-2 dark:text-white">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className={darkMode ? "text-sky-600" : "text-teal-600"}>Design Tools I Use</h4>
              <p className={darkMode ? "text-white" : "text-gray-600"}>Photoshop</p>
              <p className={darkMode ? "text-white" : "text-gray-600"}>Illustrator</p>
              <p className={darkMode ? "text-white" : "text-gray-600"}>Figma</p>
              <p className={darkMode ? "text-white" : "text-gray-600"}>Indesign</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a Frontend AngularJS and Software Engineer developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, UI/UX design,
              programming, simple MERN stack web sites.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt=""
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}